sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: OwBd98FWwORcNE58/WiLDSzvpJhFuTAP7AlpZyq/siUufkB0itXUxoGPuSDZyYaU367RJ9q6dIS4PrazFwHDRRdPBTX5GBYY74uY5BWtPZpo28JcwjaEftQpUlCRuIiBVG4bBVsZmoKsLgF6MA/2YO4RVDMAMoDPcjWgplb4odt/79YjFaeMhcCDY7f8Rr5SqGvh0yr2uyNF1XhpjtTuPs3I9FxncMBVTy8OUHIVY8k9J2gNN64trUuPtRCS1kk5Q7jRWSWxDWrcEXHjmgZLCppnFr1ZS53XLu6sbg5ta8NCatmyxHFkRRSds+LgNee6v+6uAg6ER6NQY6sF4wHn7ZxXtZ2GgP+XfYig1Oi5qsySjxAI5ZlIeVV0Ed04j+o+aCAZSrfSRehUMkUgJlfDlRY1jYkmBF6Tq5HjF91Ttoa/l0a4vgM5wdL5nZB+2bcnMMmvFZ+FrNdfb1J9IB3Ozm1+alyzyp0kF+XWhg5DJJ5EThqZfq+kWDDH5+EGEaVzm4vPqk+XABf7kX7tIU3UGv1xkUvKqNBHmVP3oPE1hFk+ame11ynFwYLLhOUm3gIc5wSAlZQL0Yqx+PkWtYf0op8IGlJlZR411nuS134x92X0PPvE3FffMvgPRW+dK3oY6prUwY3pWdBlNcWLWAGYELYTQUResdTDP68c0Za8R98=
  - secure: hASiB0aqrIlWfcVEpd3l1YNPWsTYiXE41SwKKVlBLd4UEIe43UhHrqdtFujdEHjqyJ4R5VQCfKPkgbu61XJnSK/d1Oc4gI2ghrIaT294I2VqrJONciy1tcMclaWfnDPIasMXggsrlSnbUjdJK891hl5CsJ0aOSwHzNZ5DYC/EyNzqO8sde3c+iUrAq5EURyb4VDTESELv3Fi5sn8s9JSFMTYnjzUz5H+gi4v8inIy4Y6RQ0+8rS9mEeaFGPWrFsVTvcyQmrTZfAKuhmknwt2UtzNgQskMatlwK8Z8brGFUoWSPsIahDQX/5Vn3ZYR2vYtbVoWEpb/+fGM3HMbTrENptFYsPsWffQr+xkq6Isr0IntTVQIBTgTrTq45MYPIphZTPEClL19QOEEDkluUcWTvJlOO+AK5aE7ZDGAVC1LGCPuX9aBA2yw1TkA7P6VKY9AJZU41Arsd25PgcstmE3dKAdRyYxbjoso2uGYTKTvuMqCez0lhztrdL+B4n1G5Wt1Xs1K0oN7mEl6iYcvw3QUp9MIp3u99/bkIE/eM+CbSikg7wuBRrJqi4G9r8fcRSAWuuDTqtQdzJnuXkKxCg01hgJayQZYw/xvHfOgHJvHsZmxRgW3AjI4kSvr6YICaGffQqahj0ND/WIVxFfJXzqf6vDWFGXLKHI4bMZKdWhTtc=
